[tox]
# https://github.com/tox-dev/tox/issues/3238
requires = tox==4.14.0

envlist = tests

[testenv:build-chemfiles]
passenv = *
setenv = CHFL_PY_INTERNAL_CHEMFILES = 1

deps =
    wheel
    cmake<4.0
    ninja
    setuptools

commands =
    pip wheel . --no-build-isolation --verbose --no-deps --check-build-dependencies --wheel-dir {envtmpdir}/dist

[testenv:tests]
package = external
package_env = build-chemfiles

commands =
    coverage run --source=chemfiles -m unittest discover -s tests -p "*.py"
    coverage xml -o .tox/coverage.xml

deps =
    coverage
    numpy
