name: Test

on:
  push:
    branches: [master]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        include:
          - os: windows-2019
            python-version: "3.8"
          - os: macos-14
            python-version: "3.8"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: setup MSVC command prompt
        uses: ilammy/msvc-dev-cmd@v1
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "tox <=4.14.0"
      - name: run tests
        run: tox
      - name: run extra checks
        run: |
          ./scripts/check-used-functions.py
      - uses: codecov/codecov-action@v4
        with:
          file: .tox/coverage.xml
          fail_ci_if_error: true
          verbose: true
